### ISSUE TITLE
実行テストが通らない

### ISSUE THREAD

**Issue by murakami1618** [ahaha0807/twitter-repl#30]
README.mdに記載している実行テストが通りません🤤

![2018-01-29 12 18 01](https://user-images.githubusercontent.com/31557087/35492223-f46c59a4-04ee-11e8-97fb-cc456abd998b.png)

**Comment by ahaha0807** [comment]
多分環境が古いからやと思う

**Comment by ahaha0807** [comment]
`app/controller` のディレクトリ構造はいま `middleware/controller` になってるから

**Comment by ahaha0807** [comment]
cloneし直すかpullするかお願いしまする

**Comment by tyokinuhata** [comment]
`node middleware/controller.js sample sampleRequests/sample.json` で通らないですけど、何が間違ってますかね...?

**Comment by ahaha0807** [comment]
npm testで走らせて欲しいっす

**Comment by ahaha0807** [comment]
あ

**Comment by ahaha0807** [comment]
ごめん実行テストの放火

**Comment by tyokinuhata** [comment]
ですです

**Comment by ahaha0807** [comment]
エラーレスポンス見してもらってもいい？

**Comment by murakami1618** [comment]
module.js:540
    throw err;
    ^

Error: Cannot find module '/Users/murato/workspace/twitter-repl/middleware/controller.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

これです〜

**Comment by ahaha0807** [comment]
あー。OK。再現した

**Comment by ahaha0807** [comment]
ちょっと確認するのでお待ちを

**Comment by tyokinuhata** [comment]
👍

**Comment by ahaha0807** [comment]
typoじゃねこれ

**Comment by ahaha0807** [comment]
typoだね

**Comment by ahaha0807** [comment]
`node middlewares/controller.js sample sampleRequests/sample.json` で実行してみて

**Comment by tyokinuhata** [comment]
あ、通りました...

**Comment by ahaha0807** [comment]
ｗｗ
ごめんね、完全に俺のミスでしたｗ

**Comment by ahaha0807** [comment]
done!
